### ISSUE TITLE
Details of obtaining the initial fine-grained weak supervision

### ISSUE THREAD

**Issue by recorderhou** [dheeraj7596/C2F#8]
Hi, thanks for uploading the code and data. I have a question about the initial fine-grained weak supervision. It seems that some of the passages included in `data/nyt/exclusive/1it` did not contain their corresponding surface name, and when I tried to use the surface name to sample passages, I could not get the same amount of passages. 
Are passages in `data/nyt/exclusive/1it` "exclusive" passages? Could you share what kind of preprocessing we should do before starting sampling? Or is there any other keyword that is used to sample passages besides label surface names? 
Thank you!

**Comment by dheeraj7596** [comment]
Some label surface names are too long and uninformative such as stocks_and_bonds, international_business. We used some pseudo class names for a few such classes.

**Comment by recorderhou** [comment]
Thanks for your helpful reply! What are those pseudo class names👀? Would you mind sharing the code that selects the initial weak supervision or uploading the initial fine-grained weak supervision of 20news?
Thanks a lot!

**Comment by dheeraj7596** [comment]
Hi,

Yes, I am working on making them available for 20news dataset very soon.
Sorry for the delay.

- Dheeraj
